services:
  api:
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "${API_PORT}:${API_PORT}"
  ui:
    env_file: .env
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - "${UI_PORT}:${UI_PORT}"
