name: PR - Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: self-hosted

    environment:
      name: ${{ github.base_ref }}

    env:
      FILE_PLAN: ${{ github.event.number || 'test' }}.plan
      BUCKET_TF: pcio-${{ github.base_ref }}-${{ secrets.AWS_ACCOUNT_ID }}-terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Global Dependencies
        run: bun install

      - name: Cache Dependencies (global)
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('bun.lock') }}

      - name: Start Docker Compose
        id: docker-compose-up
        run: |
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "UI_PORT=${{ secrets.UI_PORT }}" >> .env
          docker compose up -d

      - name: Lint (API)
        run: docker compose exec api bun run lint

      - name: Lint (UI)
        run: docker compose exec ui bun run lint

      - name: Run Code Tests (API)
        run: docker compose exec api bun test

      - name: Run Code Tests (UI)
        run: docker compose exec ui bun test

      - name: Start Service (API)
        id: docker-service-api
        run: nohup docker compose exec api bun dev & echo $! > api.pid

      - name: Start Service (UI)
        id: docker-service-ui
        run: nohup docker compose exec ui bun dev & echo $! > ui.pid

      - name: Wait for Service (API)
        run: npx wait-on http-get://localhost:${{ secrets.API_PORT }}/api

      - name: Wait for Service (UI)
        run: npx wait-on http-get://localhost:${{ secrets.UI_PORT }}

      - name: Run E2E Tests
        run: bun run e2e:ci

      - name: Kill Service (API)
        run: kill $(cat api.pid)
        if: steps.docker-service-api.outcome == 'success'

      - name: Kill Service (UI)
        run: kill $(cat ui.pid)
        if: steps.docker-service-ui.outcome == 'success'

      - name: Stop Docker Compose
        run: |
          docker compose down
          docker image prune --all --force
          docker volume prune --all --force
          docker container prune --force
        if: steps.docker-compose-up.outcome == 'success'

      - name: Initialize Terraform
        run: |
          terraform init                                    \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="bucket=${{ env.BUCKET_TF }}"   \
            -backend-config="key=state/terraform.tfstate"   \
            -var env="${{ github.base_ref }}"
        working-directory: terraform

      - name: Format Terraform
        run: terraform fmt -check
        working-directory: terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: terraform
