name: Terraform

on: workflow_dispatch

env:
  BUCKET_TF: pcio-${{ github.ref_name }}-${{ secrets.AWS_ACCOUNT_ID }}-terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04

    environment:
      name: ${{ github.ref_name }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('lib/bun.lock') }}

      - name: Initialize
        run: |
          terraform init \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="bucket=${{ env.BUCKET_TF }}"  \
            -backend-config="key=state/terraform.tfstate"   \
            -var env="${{ github.ref_name }}"

      - name: Format
        run: terraform fmt -check

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply -auto-approve
