name: Terraform
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  TF_VAR_region: us-east-1
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-24.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::605134440620:role/GitHubActions-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Initialize
        run: terraform init
      - name: Plan
        run: terraform plan
      - name: Apply
        run: terraform apply
