name: Terraform

on: workflow_dispatch

env:
  BUCKET_TF: pcio-${{ github.ref_name }}-${{ secrets.AWS_ACCOUNT_ID }}-terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04

    environment:
      name: ${{ github.ref_name }}

    env:
      FILE_PLAN: ${{ github.event.number }}.plan

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('lib/bun.lock') }}

      - name: Lint Code
        run: echo "linting..."

      - name: Start Docker
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          for i in {1..30}; do
            curl --silent --fail http://localhost:${{ secrets.PORT_API }} && break
            sleep 2
          done

      - name: Run Code Tests
        run: echo "running tests..."

      - name: Run E2E Tests
        run: echo "running e2e tests..."

      - name: Initialize
        run: |
          terraform init                                    \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="bucket=${{ env.BUCKET_TF }}"   \
            -backend-config="key=state/terraform.tfstate"   \
            -var env="${{ github.ref_name }}"

      - name: Format
        run: terraform fmt -check

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -out="${{ env.FILE_PLAN }}"

      - name: Upload Plan to S3
        run: aws s3 cp                                          \
          ${{ env.FILE_PLAN }}                                  \
          s3://${{ env.BUCKET_TF }}/plans/${{ env.FILE_PLAN }}

      # move to PR merge workflow
      # - name: Apply
      #   run: |
      #     if [[ "${{ github.ref_name }}" == "prod" ]]; then
      #       echo "Production environment - requiring manual approval"
      #       exit 1
      #     else
      #       echo "Non-prod environment - using auto-approve"
      #       terraform apply -auto-approve
      #     fi
