name: Terraform
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-24.04
    environment: ${{ github.ref_name }}
    # defaults:
    #   run:
    #     working-directory: terraform
    steps:
      - name: Ref Name
        run: echo "Env - ${{ github.ref_name }}"
      - name: AWS_REGION
        run: echo "AWS_REGION - ${{ env.AWS_REGION }}"
      - name: TF_LOG
        run: echo "TF_LOG - ${{ env.TF_LOG }}"
      - name: TF_VAR_REGION
        run: echo "TF_VAR_REGION - ${{ env.TF_VAR_REGION }}"
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1.7.0
      #   with:
      #     role-session-name: GitHub_to_AWS_via_FederatedOIDC
      #     role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      #     aws-region: ${{ env.AWS_REGION }}
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.11.0
      # - name: Checkout Code
      #   uses: actions/checkout@v4
      # - name: Cache Dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: lib/node_modules
      #     key: node-modules-${{ hashFiles('lib/bun.lock') }}
      # - name: Format
      #   run: terraform fmt -check
      # - name: Initialize
      #   run: terraform init
      # - name: Validate
      #   run: terraform validate
      # - name: Plan
      #   run: terraform plan
      # - name: Apply
      #   run: terraform apply
