name: Upload File

on: workflow_dispatch

env:
  BUCKET_TF: pcio-${{ github.ref_name }}-${{ secrets.AWS_ACCOUNT_ID }}-terraform

jobs:
  upload:
      runs-on: ubuntu-24.04

      environment:
        name: dev

      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1.7.0
          with:
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Write File
          run: touch test.txt

        - name: Upload File
          run: |
            aws s3 cp \
              ./test.txt
              s3://${{ env.BUCKET_TF }}/plans/test.txt
